name: SonarQube Analysis
on: push

jobs:

  sonarqube-analysis:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install
      
      - name: Delete SonarQube Cache
        env:
          SONAR_PROJECT_KEY: Spuchifai
        run: |
          curl -X POST -u "${{ secrets.SONAR_TOKEN }}": '${{ secrets.SONAR_HOST_URL }}api/caches/delete?keys=Spuchifai'
          
      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: -X
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: SonarQube Show Results
        run: sonar-scanner show
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      
          
     

      

